Repository ungdev/UA-api, pull requests merged in 2021-10, with the labels that each got.

#74 fix(usertype): add limit for coaches and attendants
  .env.example
  docs/doc_api/concepts.md
  seed.sql
  src/services/discord.ts
  src/utils/env.ts
Labels: urgent, ready to merge

#73 fix: correct tournaments name
  seed.sql
Labels: needed by front, ready to merge, hacktoberfest-accepted

#64 Feat/discord
  .eslintrc.json
  .prettierrc
  package.json
  schema.prisma
  src/app.ts
  src/controllers/discord/connect.ts
  src/controllers/discord/discordApi.d.ts
  src/controllers/discord/index.ts
  src/controllers/discord/openapi.yml
  src/controllers/discord/syncRoles.ts
  src/controllers/teams/lockTeam.ts
  src/middlewares/validation.ts
  src/services/discord.ts
  src/types.ts
  src/utils/discord.ts
  src/utils/env.ts
  tests/discord/connect.test.ts
  tests/discord/syncRoles.test.ts
  tests/middlewares.test.ts
  tests/teams/lockTeam.test.ts
  tsconfig.json
  yarn.lock
Labels: changes requested

#76 fix(misc): fix coach limit blocking new players in team
  .env.example
  docs/doc_api/discord.md
  docs/doc_api/fake.md
  src/operations/team.ts
  src/services/email/components.ts
  src/services/email/index.ts
  src/utils/env.ts
  tests/services/email.test.ts
Labels: urgent, ready to merge

#77 fix(tickets): optional cartItemId to return current user ticket
  .env.example
  src/controllers/teams/openapi.yml
  src/controllers/tickets/getTicket.ts
  src/controllers/tickets/index.ts
  src/controllers/tickets/openapi.yml
  tests/tickets/getTicket.test.ts
Labels: urgent, needed by front, ready to merge

#102 Corrections
  docs/doc_api/permissions.md
  src/controllers/admin/emails/getMails.ts
  src/controllers/admin/openapi.yml
  src/controllers/admin/users/forcePay.ts
  src/controllers/admin/users/getUsers.ts
  src/controllers/admin/users/updateUser.ts
  src/controllers/openapi.yml
  src/middlewares/authentication.ts
  src/operations/carts.ts
  src/operations/log.ts
  src/operations/settings.ts
  src/operations/team.ts
  src/operations/user.ts
  src/services/email/serializer.ts
  src/types.ts
  src/utils/filters.ts
  src/utils/helpers.ts
  src/utils/validators.ts
  tests/admin/users/getUsers.test.ts
  tests/admin/users/updateUser.test.ts
  tests/auth/login.test.ts
  tests/auth/validate.test.ts
  tests/services/email.test.ts
Labels: ready to merge

#98 feat(logs): admins can now see logs
  src/controllers/admin/index.ts
  src/controllers/admin/logs/index.ts
  src/controllers/admin/logs/logs.ts
  src/controllers/admin/openapi.yml
  src/middlewares/log.ts
  src/operations/log.ts
  src/types.ts
  tests/admin/logs/logs.test.ts
Labels: ready to merge
