Repository ungdev/UA-api, pull requests merged in 2021-09, with the labels that each got.

#43 getTournaments + faker
  .env.example
  README.md
  docs/doc_general/installation.md
  package.json
  src/controllers/admin/openapi.yml
  src/controllers/openapi.yml
  src/controllers/teams/getTeams.ts
  src/controllers/teams/openapi.yml
  src/controllers/tournaments/getTournaments.ts
  src/operations/tournament.ts
  src/types.ts
  src/utils/filters.ts
  tests/admin/users/updateUser.test.ts
  tests/fake.ts
  tests/setup.ts
  tests/tournaments/getTournaments.test.ts
  tests/utils.ts
Labels: needed by front

#59 feat / custom-message
  schema.prisma
  src/controllers/admin/openapi.yml
  src/controllers/admin/scan/scan.ts
  src/controllers/admin/users/getUsers.ts
  src/controllers/admin/users/updateUser.ts
  src/controllers/auth/register.ts
  src/controllers/openapi.yml
  src/operations/user.ts
  tests/admin/scan/scan.test.ts
  tests/admin/users/getUsers.test.ts
  tests/admin/users/updateUser.test.ts
  tests/utils.ts
Labels: ready to merge

#60 fix(tests): random usernames should now match validator
  tests/utils.ts
Labels: ready to merge

#62 Feat/discount ssbu
  seed.sql
  src/controllers/items/getItems.ts
  src/controllers/users/createCart.ts
  src/operations/item.ts
  src/types.ts
  tests/items/getITems.test.ts
  tests/items/getItems.test.ts
  tests/services/email.test.ts
  tests/users/createCart.test.ts
Labels: ready to merge

#67 fix(tshirt-order)
  src/operations/item.ts
Labels: ready to merge

#65 feat(user): attendants and spectators
  .gitignore
  schema.prisma
  seed.sql
  src/controllers/admin/auth/login.ts
  src/controllers/admin/openapi.yml
  src/controllers/admin/users/updateUser.ts
  src/controllers/auth/login.ts
  src/controllers/auth/openapi.yml
  src/controllers/auth/register.ts
  src/controllers/discord/openapi.yml
  src/controllers/openapi.yml
  src/controllers/teams/createTeam.ts
  src/controllers/teams/createTeamRequest.ts
  src/controllers/tournaments/openapi.yml
  src/controllers/users/createCart.ts
  src/controllers/users/index.ts
  src/controllers/users/openapi.yml
  src/controllers/users/spectate.ts
  src/controllers/users/updateUser.ts
  src/middlewares/team.ts
  src/middlewares/user.ts
  src/operations/carts.ts
  src/operations/log.ts
  src/operations/team.ts
  src/operations/user.ts
  src/types.ts
  src/utils/env.ts
  src/utils/filters.ts
  src/utils/validators.ts
  tests/admin/auth/login.test.ts
  tests/admin/users/getUsers.test.ts
  tests/admin/users/updateUser.test.ts
  tests/auth/login.test.ts
  tests/auth/register.test.ts
  tests/middlewares.test.ts
  tests/services/email.test.ts
  tests/teams/createTeam.test.ts
  tests/teams/createTeamRequest.test.ts
  tests/users/createCart.test.ts
  tests/users/createSpectator.test.ts
  tests/users/deleteSpectator.test.ts
  tests/users/updateUser.test.ts
  tests/utils.ts
Labels: urgent, ready to merge

#68 fix(discount-ssbu): don't allow more than one discount per player
  src/controllers/users/createCart.ts
  src/types.ts
  tests/users/createCart.test.ts
Labels: ready to merge

#63 fix: explicited invalidbody
  src/controllers/admin/scan/scan.ts
  src/controllers/teams/createTeam.ts
  src/controllers/teams/createTeamRequest.ts
  src/controllers/users/createCart.ts
  src/middlewares/validation.ts
  src/types.ts
  src/utils/validators.ts
  tests/admin/scan/scan.test.ts
  tests/admin/users/replace.test.ts
  tests/admin/users/updateUser.test.ts
  tests/auth/askResetPassword.test.ts
  tests/auth/login.test.ts
  tests/auth/register.test.ts
  tests/auth/resetPassword.test.ts
  tests/root/contact.test.ts
  tests/teams/createTeam.test.ts
  tests/teams/createTeamRequest.test.ts
  tests/teams/updateTeam.test.ts
  tests/users/createCart.test.ts
  tests/users/updateUser.test.ts
Labels: changes requested

#69 fix(deps): updating dependencies
  .eslintrc.json
  Dockerfile
  package.json
  schema.prisma
  src/controllers/admin/users/updateUser.ts
  src/controllers/auth/register.ts
  src/controllers/discord/oauth.ts
  src/controllers/teams/createTeam.ts
  src/controllers/teams/updateTeam.ts
  src/controllers/users/createCart.ts
  src/controllers/users/openapi.yml
  src/controllers/users/updateUser.ts
  src/middlewares/validation.ts
  src/operations/carts.ts
  src/operations/item.ts
  src/utils/env.ts
  tests/admin/auth/login.test.ts
  tests/admin/carts/refund.test.ts
  tests/admin/scan/scan.test.ts
  tests/admin/users/forcePay.test.ts
  tests/admin/users/getCarts.test.ts
  tests/admin/users/getUsers.test.ts
  tests/admin/users/replace.test.ts
  tests/admin/users/updateUser.test.ts
  tests/discord/oauth.test.ts
  tests/etupay/callback.test.ts
  tests/services/email.test.ts
  tests/setup.ts
  tests/teams/acceptRequest.test.ts
  tests/teams/cancelTeamRequest.test.ts
  tests/teams/createTeam.test.ts
  tests/teams/createTeamRequest.test.ts
  tests/teams/deleteTeam.test.ts
  tests/teams/kickUser.test.ts
  tests/teams/leaveTeam.test.ts
  tests/teams/lockTeam.test.ts
  tests/teams/promoteCaptain.test.ts
  tests/teams/refuseTeamRequest.test.ts
  tests/teams/updateTeam.test.ts
  tests/tickets/getTicket.test.ts
  tests/tournaments.ts
  tests/users/createCart.test.ts
  tests/users/createSpectator.test.ts
  tests/users/deleteSpectator.test.ts
  tests/users/getCarts.test.ts
  tests/users/updateUser.test.ts
  tests/utils/pdf.test.ts
  tsconfig.json
  yarn.lock
Labels: ready to merge

#70 feat(reservation): added a whitelist for chosen tournament
  src/controllers/teams/createTeam.ts
  src/middlewares/whitelist.ts
  src/types.ts
  tests/teams/createTeam.test.ts
  whitelist.json
Labels: ready to merge

#72 fix(tickets): add username to ticket holders
  src/controllers/openapi.yml
  src/operations/carts.ts
  src/utils/env.ts
  src/utils/filters.ts
  tests/admin/users/getCarts.test.ts
  tests/users/getCarts.test.ts
Labels: needed by front, ready to merge

#71 docs(api): added concepts.md
  docs/doc_api/concepts.md
  docs/doc_api/integration.md
  docs/doc_general/deadlines.md
  docs/doc_general/installation.md
Labels: ready to merge
